### ISSUE TITLE
HOWTO: manage general purpose channels

### ISSUE THREAD

**Issue by G3z** [vic/apollo-phoenix-websocket#15]
While waiting for subscriptions support both here and in absinthe I though of building a custom pubsub mechanism to inform the clients when they should update. To do so i should be able to handle the websockets events in my application (for example join-room, new-chat-message, ...) I was wondering if it's possible to do so while using this library and how would you suggest doing it (or why not)

**Comment by vic** [comment]
Hey @G3z,

We are *almost* done with GQL subscription, I just need a bit a time to fix the remaining merge conflicts on that branch, and would certainly be thankful if you'd want to help me test that branch with either the absinthe subscriptions example or with your own use case. I'll do my best to try giving this a couple of hours today and ping you back with some instructions/example on how to test. 

Otherwise, (in case that neither you nor I have time for advancing the PR) I guess you could use [Apollo.watchQuery](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient\.watchQuery) with the `pollInterval` option. That would not be as ideal as an actual GQL subscription, but I guess in the mean time you might consider having a query polling to the server.

**Comment by G3z** [comment]
uh I didn't know you were so close, sorry.
I missed the "absinthe subscriptions example" you are talking about 🤔
I'd be happy to help!

**Comment by G3z** [comment]
Maybe i should open an appropriate branch but...
I tried the subscription branch
I made a subscription which I tested in graphiql (I cloned a query)
In my app nothing appears (not even an error
but when i unmount the component i receive this
```
Unhandled JS Exception: f.apply(...).then is not a function
```
generated from
```
function unsubscribe (subID) {
    const processReponse = subscriptions[subID]
    const doUnsubscribe = connect.bind(
      null, sockets, performUnsubscribe.bind(null, processReponse))
    pipeP(requestMiddleware, doUnsubscribe)({subID}) // here
  }
```
```
module.exports = function _pipeP(f, g) {
  return function() {
    var ctx = this;
    return f.apply(ctx, arguments).then(function(x) { // this throws
      return g.call(ctx, x);
    });
  };
};

```

**Comment by vic** [comment]
Lets close this and keep progress on #9
